version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "7154:80"   
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=trips
      - DB_USER=postgres
      - DB_PASSWORD=admin
    volumes:
      - ./backend/backend/Images:/app/Images  

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: trips
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: 
